version: "3.9"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    stdin_open: true
    tty: true
    restart: always
    volumes:
     - /volumes/homepage/config:/app/config
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
        ipv4_address: "172.20.0.16"
networks:
  default:
    name: static
    external: true
